In [1]:
# summaflow library
from summaflow import (
    Stats,
    GeoLayer,
)

# 3rd party libraries
import pandas as pd
import numpy as np

# built-in libraries
import os

In [2]:
root_path = '../test-stats/'
stat_file = os.path.join(root_path, 'summaflow_stats_NA_NALCMS_landcover_2020_30m.csv')

sample = pd.read_csv(stat_file, header=0, index_col=0)

In [3]:
s = Stats.from_maf(stat_file)

Based on the mapping table above, the arithmetics are summation and re-normalization by removing one or more land classes in the source dataset.

In [4]:
# keys: source landcover dataset, for example, here is NALCMS
# values: MODIS equivalent classes, that is one of SUMMA's options
landcover_mapping = {
    18: 17,
    1: 4,
    5: 7,
    8: None,
    0: None,
    2: 3,
    6: 3,
    10: 3,
    11: 3,
    14: 3,
    15: 3,
    16: 3,
    17: 11,
    19: None,
}
# in the example above, the following mappings are implemented:
#  NALCMS       MODIS
#  18           17
#  1 & 3        4
#  5            7
#  7            9
#  8            None of the classes, so drop it

In [5]:
s.stats

{'frac', 'majority', 'max', 'mean', 'median', 'min', 'minority', 'q'}

In [6]:
# df = s.map_fracs(landcover_mapping, inplace=False).copy()

In [7]:
s.set_frac_threshold(0.2, inplace=True)

,frac_0,frac_2,frac_5,frac_6,frac_8,frac_10,frac_11,frac_12,frac_13,frac_14,frac_15,frac_16,frac_17,frac_18,frac_19
COMID,,,,,,,,,,,,,,,
71000092,0.0,0.00000,0.000000,0.000000,0.284378,0.060045,0.0,0.0,0.0,0.004291,0.000000,0.000000,0.000000,0.651287,0.0
71007360,0.0,0.00058,0.002671,0.000088,0.510002,0.126497,0.0,0.0,0.0,0.011424,0.000000,0.005740,0.000000,0.342999,0.0
71011339,0.0,0.00000,0.017300,0.000000,0.248423,0.000000,0.0,0.0,0.0,0.194937,0.000000,0.062901,0.000000,0.476439,0.0
71022453,0.0,0.00000,0.002760,0.000000,0.009170,0.012962,0.0,0.0,0.0,0.031292,0.824023,0.001044,0.072253,0.046496,0.0
71028389,0.0,0.00000,0.006680,0.000000,0.010694,0.002952,0.0,0.0,0.0,0.021401,0.881859,0.000000,0.038318,0.038096,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71048311,0.0,0.00000,0.000000,0.000000,0.000000,0.000137,0.0,0.0,0.0,0.022039,0.288019,0.000000,0.667526,0.022279,0.0
71048310,0.0,0.00000,0.003596,0.000000,0.000000,0.000425,0.0,0.0,0.0,0.086960,0.488488,0.000537,0.389940,0.030053,0.0
71048309,0.0,0.00000,0.000000,0.000000,0.000000,0.002177,0.0,0.0,0.0,0.218178,0.527674,0.000000,0.164703,0.087267,0.0
71048308,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.234646,0.639731,0.000000,0.000000,0.125623,0.0
71047031,0.0,0.00000,0.002796,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.049634,0.880878,0.000000,0.041225,0.025466,0.0

In [8]:
s['majority']

          majority
COMID
71000092         1
71007360         8
71011339         1
71022453        15
71028389        15
...            ...
71048311        17
71048310        15
71048309        15
71048308        15
71047031        15

[48951 rows x 1 columns]

In [9]:
s._update_stats()

/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:451: FutureWarning: The behavior of DataFrame.idxmin with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  self.minority = self['frac'].replace(0, np.nan).idxmin(axis=1)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:454: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  self.majority = self['frac'].replace(0, np.nan).idxmax(axis=1)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:466: UserWarning: Some elements do not cover any classes, therefore, corresponding `min` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:478: UserWarning: Some elements do not cover any classes, therefore, corresponding `max` is set to `np.nan`.
  warnings.warn(wrn_msg)

In [13]:
s.data

,min,max,mean,median,majority,minority,q10,q50,q90,frac_0,...,frac_10,frac_11,frac_12,frac_13,frac_14,frac_15,frac_16,frac_17,frac_18,frac_19
COMID,,,,,,,,,,,,,,,,,,,,,
71000092,1,18,6.955233,6.882406,1,14,2.176481,6.882406,16.593682,0.0,...,0.060045,0.0,0.0,0.0,0.004291,0.000000,0.000000,0.000000,0.651287,0.0
71007360,1,18,8.395402,8.074468,8,6,1.318079,8.074468,17.151368,0.0,...,0.126497,0.0,0.0,0.0,0.011424,0.000000,0.005740,0.000000,0.342999,0.0
71011339,1,18,2.551205,3.261133,1,5,1.452227,3.261133,8.460857,0.0,...,0.000000,0.0,0.0,0.0,0.194937,0.000000,0.062901,0.000000,0.476439,0.0
71022453,5,18,15.097147,14.944646,15,16,14.126234,14.944646,16.306085,0.0,...,0.012962,0.0,0.0,0.0,0.031292,0.824023,0.001044,0.072253,0.046496,0.0
71028389,5,18,15.013106,14.783442,15,10,14.115224,14.783442,16.659281,0.0,...,0.002952,0.0,0.0,0.0,0.021401,0.881859,0.000000,0.038318,0.038096,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71048311,10,18,16.379164,16.035639,17,10,14.587728,16.035639,17.471348,0.0,...,0.000137,0.0,0.0,0.0,0.022039,0.288019,0.000000,0.667526,0.022279,0.0
71048310,1,18,15.741898,15.618678,15,1,14.177869,15.618678,16.957337,0.0,...,0.000425,0.0,0.0,0.0,0.086960,0.488488,0.000537,0.389940,0.030053,0.0
71048309,1,18,15.344791,14.916059,15,1,14.021145,14.916059,17.167103,0.0,...,0.002177,0.0,0.0,0.0,0.218178,0.527674,0.000000,0.164703,0.087267,0.0
71048308,14,18,15.142223,14.901695,15,18,14.180339,14.901695,17.326582,0.0,...,0.000000,0.0,0.0,0.0,0.234646,0.639731,0.000000,0.000000,0.125623,0.0
71047031,1,18,15.077705,14.854769,15,1,14.138138,14.854769,16.655808,0.0,...,0.000000,0.0,0.0,0.0,0.049634,0.880878,0.000000,0.041225,0.025466,0.0