In [1]:
# summaflow library
from summaflow import (
    Stats,
    GeoLayer,
)

# 3rd party libraries
import pandas as pd
import numpy as np

# built-in libraries
import os

In [2]:
root_path = '../test-stats/'
stat_file = os.path.join(root_path, 'summaflow_stats_NA_NALCMS_landcover_2020_30m.csv')

sample = pd.read_csv(stat_file, header=0, index_col=0)

In [3]:
s = Stats.from_maf(stat_file)

Based on the mapping table above, the arithmetics are summation and re-normalization by removing one or more land classes in the source dataset.

In [4]:
# keys: source landcover dataset, for example, here is NALCMS
# values: MODIS equivalent classes, that is one of SUMMA's options
landcover_mapping = {
    18: 17,
    1: 4,
    5: 7,
    8: None,
    0: None,
    2: 3,
    6: 3,
    10: 3,
    11: 3,
    14: 3,
    15: 3,
    16: 3,
    17: 11,
    19: None,
}
# in the example above, the following mappings are implemented:
#  NALCMS       MODIS
#  18           17
#  1 & 3        4
#  5            7
#  7            9
#  8            None of the classes, so drop it

In [5]:
s.stats

{'count',
 'frac',
 'majority',
 'max',
 'mean',
 'median',
 'min',
 'minority',
 'q',
 'variety'}

In [6]:
df1 = s.map_fracs(landcover_mapping, inplace=True, autoupdate_stats=True)

/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:612: UserWarning: Some elements do not cover any classes, therefore, corresponding `min` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:625: UserWarning: Some elements do not cover any classes, therefore, corresponding `max` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:643: UserWarning: Some elements do not cover any classes, therefore, corresponding `max` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:675: UserWarning: The following stats were not updated: {'median', 'q', 'count'}
  warnings.warn(wrn_msg)

In [7]:
df2 = s.set_frac_threshold(0.2, inplace=False, autoupdate_stats=True)

/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:612: UserWarning: Some elements do not cover any classes, therefore, corresponding `min` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:625: UserWarning: Some elements do not cover any classes, therefore, corresponding `max` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:643: UserWarning: Some elements do not cover any classes, therefore, corresponding `max` is set to `np.nan`.
  warnings.warn(wrn_msg)
/Users/kasrakeshavarz/Documents/github-repos/summa-model-specific/src/summaflow/geospatial.py:675: UserWarning: The following stats were not updated: {'median', 'q', 'count'}
  warnings.warn(wrn_msg)

In [8]:
df1

,frac_3,frac_4,frac_7,frac_12,frac_13,frac_17,min,max,mean,median,...,q10,q50,q90,variety,frac_3,frac_4,frac_7,frac_12,frac_13,frac_17
COMID,,,,,,,,,,,,,,,,,,,,,
71000092,0.032020,0.643825,0.000000,0.0,0.0,0.324155,3,17,8.181992,6.882406,...,2.176481,6.882406,16.593682,3,0.032020,0.643825,0.000000,0.0,0.0,0.324155
71007360,0.152174,0.483365,0.002817,0.0,0.0,0.361644,3,17,8.557654,8.074468,...,1.318079,8.074468,17.151368,4,0.152174,0.483365,0.002817,0.0,0.0,0.361644
71011339,0.030766,0.910319,0.002064,0.0,0.0,0.056851,3,17,4.714484,3.261133,...,1.452227,3.261133,8.460857,4,0.030766,0.910319,0.002064,0.0,0.0,0.056851
71022453,0.946378,0.000000,0.003004,0.0,0.0,0.050617,3,17,3.720660,14.944646,...,14.126234,14.944646,16.306085,3,0.946378,0.000000,0.003004,0.0,0.0,0.050617
71028389,0.952916,0.000000,0.007024,0.0,0.0,0.040060,3,17,3.588930,14.783442,...,14.115224,14.783442,16.659281,3,0.952916,0.000000,0.007024,0.0,0.0,0.040060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71048311,0.932991,0.000000,0.000000,0.0,0.0,0.067009,3,17,3.938130,16.035639,...,14.587728,16.035639,17.471348,2,0.932991,0.000000,0.000000,0.0,0.0,0.067009
71048310,0.944462,0.000404,0.005892,0.0,0.0,0.049243,3,17,3.713368,15.618678,...,14.177869,15.618678,16.957337,4,0.944462,0.000404,0.005892,0.0,0.0,0.049243
71048309,0.894230,0.001446,0.000000,0.0,0.0,0.104324,3,17,4.461978,14.916059,...,14.021145,14.916059,17.167103,3,0.894230,0.001446,0.000000,0.0,0.0,0.104324
71048308,0.874377,0.000000,0.000000,0.0,0.0,0.125623,3,17,4.758724,14.901695,...,14.180339,14.901695,17.326582,2,0.874377,0.000000,0.000000,0.0,0.0,0.125623
71047031,0.970268,0.000263,0.002915,0.0,0.0,0.026554,3,17,3.383681,14.854769,...,14.138138,14.854769,16.655808,4,0.970268,0.000263,0.002915,0.0,0.0,0.026554

In [9]:
df2

,frac_7,frac_12,frac_13,frac_17,min,max,mean,median,majority,minority,...,q10,q50,q90,variety,frac_3,frac_4,frac_7,frac_12,frac_13,frac_17
COMID,,,,,,,,,,,,,,,,,,,,,
71000092,0.000000,0.0,0.0,1.000000,17,17,17.000000,6.882406,17,17,...,2.176481,6.882406,16.593682,1,0.032020,0.643825,0.000000,0.0,0.0,0.324155
71007360,0.007728,0.0,0.0,0.992272,7,17,16.922720,8.074468,17,7,...,1.318079,8.074468,17.151368,2,0.152174,0.483365,0.002817,0.0,0.0,0.361644
71011339,0.035038,0.0,0.0,0.964962,7,17,16.649617,3.261133,17,7,...,1.452227,3.261133,8.460857,2,0.030766,0.910319,0.002064,0.0,0.0,0.056851
71022453,0.056026,0.0,0.0,0.943974,7,17,16.439740,14.944646,17,7,...,14.126234,14.944646,16.306085,2,0.946378,0.000000,0.003004,0.0,0.0,0.050617
71028389,0.149183,0.0,0.0,0.850817,7,17,15.508170,14.783442,17,7,...,14.115224,14.783442,16.659281,2,0.952916,0.000000,0.007024,0.0,0.0,0.040060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71048311,0.000000,0.0,0.0,1.000000,17,17,17.000000,16.035639,17,17,...,14.587728,16.035639,17.471348,1,0.932991,0.000000,0.000000,0.0,0.0,0.067009
71048310,0.106865,0.0,0.0,0.893135,7,17,15.931350,15.618678,17,7,...,14.177869,15.618678,16.957337,2,0.944462,0.000404,0.005892,0.0,0.0,0.049243
71048309,0.000000,0.0,0.0,1.000000,17,17,17.000000,14.916059,17,17,...,14.021145,14.916059,17.167103,1,0.894230,0.001446,0.000000,0.0,0.0,0.104324
71048308,0.000000,0.0,0.0,1.000000,17,17,17.000000,14.901695,17,17,...,14.180339,14.901695,17.326582,1,0.874377,0.000000,0.000000,0.0,0.0,0.125623
71047031,0.098924,0.0,0.0,0.901076,7,17,16.010764,14.854769,17,7,...,14.138138,14.854769,16.655808,2,0.970268,0.000263,0.002915,0.0,0.0,0.026554

In [10]:
s['frac']

            frac_3    frac_4    frac_7  frac_12  frac_13   frac_17
COMID
71000092  0.032020  0.643825  0.000000      0.0      0.0  0.324155
71007360  0.152174  0.483365  0.002817      0.0      0.0  0.361644
71011339  0.030766  0.910319  0.002064      0.0      0.0  0.056851
71022453  0.946378  0.000000  0.003004      0.0      0.0  0.050617
71028389  0.952916  0.000000  0.007024      0.0      0.0  0.040060
...            ...       ...       ...      ...      ...       ...
71048311  0.932991  0.000000  0.000000      0.0      0.0  0.067009
71048310  0.944462  0.000404  0.005892      0.0      0.0  0.049243
71048309  0.894230  0.001446  0.000000      0.0      0.0  0.104324
71048308  0.874377  0.000000  0.000000      0.0      0.0  0.125623
71047031  0.970268  0.000263  0.002915      0.0      0.0  0.026554

[48951 rows x 6 columns]